### ISSUE TITLE
ID3QNE-main.py中224行中bug请教

### ISSUE THREAD

**Issue by Rongxuecheng** [CaryLi666/ID3QNE-algorithm#2]
您好 在复现您的代码时 ID3QNE-main.py中224行 batch_uids = range(1, batch_s) 运行报错，因为batch_s此时是一个数组类型，而不是整形，想请问一下您这个batch_uids是用来做什么的呢，望不吝指教，感谢
![image](https://user-images.githubusercontent.com/48374106/226566281-4ec39a88-40d1-4b23-b531-fefef0b83068.png)

**Comment by Dreamfs** [comment]
请问您的问题最后得到解决了吗，我也有相同的问题
